const REPLACEMENTS: Array<[RegExp, string]> = [
  [/Story Bible/gi, '故事设定集'],
  [/Story Package/gi, '故事资料包'],
  [/Story Directions?/gi, '故事方向'],
  [/Storyboards?/gi, '分镜'],
  [/Animatic/gi, '节奏样片'],
  [/Pre-production/gi, '前期制作'],
  [/Hero Shot/gi, '主镜头'],
  [/Hybrid Preview/gi, '混合小样'],
  [/Preview/gi, '小样'],
  [/Timeline/gi, '时间线'],
  [/Revision/gi, '局部修改'],
  [/Change Set/gi, '变更集'],
  [/Lip Sync/gi, '口型同步'],
  [/Dialogue/gi, '对白'],
  [/Ambience/gi, '环境音'],
  [/SFX/gi, '音效'],
  [/BGM/gi, '背景音乐'],
  [/Audio/gi, '音频'],
  [/Video/gi, '视频'],
  [/Take/gi, '版本'],
  [/Candidate/gi, '候选'],
  [/Look Bible/gi, '造型设定'],
  [/Look Version/gi, '造型版本'],
  [/\bLook\b/gi, '造型'],
  [/Mock/gi, '模拟'],
  [/Export/gi, '导出'],
  [/Worker/gi, '后台任务进程'],
  [/\bScript\b/gi, '剧本'],
  [/\bOutline\b/gi, '分集大纲'],
  [/\bShot\b/gi, '镜头'],
  [/\bScene\b/gi, '场景'],
  [/\bProject\b/gi, '项目'],
  [/\bpoints?\b/gi, '积分'],
]

const EXACT_LABELS: Record<string, string> = {
  urban_drama: '都市情感',
  urban_romance: '都市甜宠',
  urban_suspense: '都市悬疑',
  suspense: '悬疑',
  family_drama: '家庭伦理',
  revenge: '复仇逆袭',
  costume_romance: '古装爱情',
  costume_intrigue: '古装权谋',
  youth_campus: '青春校园',
  workplace: '职场故事',
  comedy: '喜剧',
  fantasy: '奇幻',
  action_crime: '动作犯罪',
  sci_fi: '科幻',
  ACTION: '动作',
  ABILITY: '能力认证',
  AMBIENCE: '环境音',
  ANTAGONIST: '反派',
  APPROVED: '已批准',
  BGM: '背景音乐',
  CLEARED: '已确认',
  DIALOGUE: '对白',
  DOLLY_IN: '推镜',
  EMOTIONAL_ESCALATION: '情绪升级',
  FAILED: '失败',
  IDENTITY: '身份认证',
  NIGHT: '夜',
  DAY: '日',
  NARRATION: '旁白',
  GLOBAL: '全局',
  HANDHELD: '手持',
  MCU: '中近景',
  MS: '中景',
  MORALITY: '品格认证',
  PACING: '节奏',
  PAN: '摇镜',
  PROTAGONIST: '主角',
  READY: '已就绪',
  RESOURCE: '资源认证',
  SFX: '音效',
  STATIC: '固定镜头',
  SUPPORTING: '配角',
  SIDECAR: '外挂字幕',
  SUBTITLE: '字幕',
  VIDEO: '视频',
  VOICE_OVER: '画外音',
  TRACK: '跟拍',
  TRUTH: '真相认证',
  CU: '近景',
  WS: '全景',
  'Douyin Vertical': '抖音竖屏',
}

export function localizeDisplayText(value: string): string {
  if (EXACT_LABELS[value]) return EXACT_LABELS[value]
  return REPLACEMENTS.reduce(
    (result, [pattern, replacement]) => result.replace(pattern, replacement),
    value,
  )
}
